### ISSUE TITLE
Error in Building project

### ISSUE THREAD

**Issue by hrishiballal** [IvanSanchez/Leaflet.VectorGrid#18]
The documentation says 

> Use the file dist/Leaflet.VectorGrid.js if you are adding these dependencies yourself, or dist/Leaflet.VectorGrid.bundled.js for minimal fuss.

However there is no bundled file in the repository using the following steps:
1) Download the repository
2) Run ```npm install```
3) Then I put in ```npm install --save-dev gobble ```
4) Then I run ```build-depe
5) The output is following 
``` shell
Bundling and compressing 75 files...
	Uncompressed: 364.15 KB (+2 bytes)
	Saved to dist/leaflet-src.js
	Compressed: 139.29 KB (+2 bytes)
	Saved to dist/leaflet.js
	Gzipped: 37.48 KB (+1 bytes)
```
6) Then I run ```gobble``` and output is following
``` shell
gobble: error starting gobble
>>>
Cannot find module './get-source-node'
Error: Cannot find module './get-source-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/username/Downloads/Leaflet.VectorGrid-master/node_modules/gobble-concat/gobble-concat.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
<<<
```
This is a error with gobble-concat.

**Comment by hrishiballal** [comment]
I downloaded the get-source-node module file from [here](https://raw.githubusercontent.com/gobblejs/gobble-unpackage/master/get-source-node.js)

and put it in the gobble-concat directory and I have the build now.
